import { BRAND_COLOR } from "../../components/ui/constants";

export const defaultConfig = {
  bgOpacity: 70,
  imageUrl: "https://placehold.co/310x400/e2e8f0/94a3b8?text=PNG+Image",
  deeplink: "https://yourapp.com/deeplink",
  buttonCount: 2,
  btnText: "Get Reward",
  btnText2: "Close",
  btnFont: "Pretendard",
  btnWeight: "700",
  btnSize: 15,
  btnColor: "#ffffff",
  btnBgColor: BRAND_COLOR,
  btn2Color: "#ffffff",
  btn2BgColor: "#64748b",
  btnRadius: 4,
  bottomLeftText: "Don't show again",
  bottomRightText: "Close",
  bottomColor: "#ffffff",
  btnTracking: "button",
  btn2Tracking: "close",
  bottomLeftTracking: "never show",
  bottomRightTracking: "close",
  enableLogClick: true,
  enableCustomEvent: false,
  customEventName: "",
  enableDismissAttribute: false,
};
