import { makeNormalize } from "../figma-shared/makeNormalize.js";

export const defaultConfig = {
  bgOpacity: 70,
  cardWidth: 299,
  cardBg: "#ffffff",
  cardPaddingX: 20,
  cardPaddingTop: 26,
  cardPaddingBottom: 20,
  iconSize: 70,
  iconUrl: "https://placehold.co/70x70/e2e8f0/64748b?text=!",
  iconGap: 16,
  titleText: "My Comeback as the Youngest Member",
  subtitleText: "If you read New Series more than 3 times, you will receice 3 Coins.",
  titleSize: 20,
  subtitleSize: 13,
  titleColor: "#000000",
  subtitleColor: "#000000",
  titleFont: "Inter",
  subtitleFont: "Inter",
  btnText: "txt1",
  btnFont: "Inter",
  btnWeight: "700",
  btnSize: 15,
  btnColor: "#ffffff",
  btnBgColor: "#00dc64",
  btnHeight: 46,
  btnRadius: 4,
  textBlockGap: 7,
  deeplink: "https://yourapp.com/deeplink",
  bottomLeftText: "Don't show again",
  bottomRightText: "Close",
  bottomColor: "#ffffff",
  btnTracking: "cta",
  bottomLeftTracking: "never show",
  bottomRightTracking: "close",
  enableLogClick: true,
  enableCustomEvent: false,
  customEventName: "",
};

export const normalizeFigmaAlarmConfig = makeNormalize(defaultConfig);
