import { BRAND_COLOR } from "../../components/ui/constants";

export const defaultConfig = {
  bgOpacity: 70,
  bgColor: "#F5F5DC",
  bgRadius: 14,
  bgImage: "",
  imageUrl: "https://placehold.co/295x295/e2e8f0/94a3b8?text=Image",
  imageRadius: 4,
  deeplink: "https://yourapp.com/deeplink",
  titleText: "Special Offer!",
  titleFont: "Pretendard",
  titleWeight: "700",
  titleSize: 20,
  titleColor: "#000000",
  titleAlign: "center",
  subText: "Complete 5 episodes today and get 10 Coins instantly!",
  subFont: "Pretendard",
  subWeight: "400",
  subSize: 13,
  subColor: "#000000",
  subAlign: "center",
  buttonCount: 2,
  btnText: "Get Reward",
  btnText2: "Close",
  btnFont: "Pretendard",
  btnWeight: "700",
  btnSize: 15,
  btnColor: "#ffffff",
  btnBgColor: BRAND_COLOR,
  btn2Color: "#ffffff",
  btn2BgColor: "#64748b",
  btnRadius: 4,
  bottomLeftText: "Don't show again",
  bottomRightText: "Close",
  bottomColor: "#ffffff",
  btnTracking: "button",
  btn2Tracking: "close",
  bottomLeftTracking: "never show",
  bottomRightTracking: "close",
  enableLogClick: true,
  enableCustomEvent: false,
  customEventName: "",
  enableDismissAttribute: false,
};
