import { makeNormalize } from "../figma-shared/makeNormalize.js";

export const defaultConfig = {
  bgOpacity: 70,
  cardWidth: 310,
  slideImageWidth: 270,
  slideImageHeight: 180,
  slideGap: 10,
  imageUrl1: "/figma-modal-hero.jpg",
  imageUrl2: "/figma-modal-hero.jpg",
  imageUrl3: "/figma-modal-hero.jpg",
  slideAutoPlay: false,
  slideAutoPlayMs: 3000,
  slideRadius: 4,
  pagerBg: "rgba(0,0,0,0.8)",
  titleText: "My Comeback as the Youngest Member",
  subtitleText: "If you read New Series more than 3 times, you will receice 3 Coins.",
  titleSize: 20,
  subtitleSize: 13,
  titleColor: "#000000",
  subtitleColor: "#000000",
  btnText: "txt1",
  btnFont: "Inter",
  btnWeight: "700",
  btnSize: 15,
  btnColor: "#ffffff",
  btnBgColor: "#00dc64",
  btnHeight: 46,
  btnRadius: 4,
  cardBg: "#ffffff",
  cardPaddingX: 20,
  cardPaddingTop: 14,
  cardPaddingBottom: 20,
  deeplink: "https://yourapp.com/deeplink",
  bottomLeftText: "Don't show again",
  bottomRightText: "Close",
  bottomColor: "#ffffff",
  bottomSideMargin: 0,
  btnTracking: "cta",
  bottomLeftTracking: "never show",
  bottomRightTracking: "close",
  enableLogClick: true,
  enableCustomEvent: false,
  customEventName: "",
};

export const normalizeFigmaSlideHConfig = makeNormalize(defaultConfig);
